name: calculator PR

on:
  pull_request:
    types: [opened, edited]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.6
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.6
      - name: Build
        run: go build -v ./...
      - name: Test
        uses: robherley/go-test-action@v0.2.0
        with:
          testArguments: '-v ./... -tags unit,integration'

      